[package]
name = "filehost-adapter"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web = "4"
env_logger = "0.11.5"
hcl-rs = "0.18.2"
log = "0.4.22"
reqwest = { version = "0.12.9", features = ["multipart"] }
serde = { version = "1.0.215", features = ["derive"] }
