name: Build docker images

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GCHR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
      - name: Build
        uses: docker/build-push-action@v6
        if: ${{ github.event_name == 'pull_request' }}
        with:
          platforms: linux/amd64,linux/arm64
          outputs: type=cacheonly
          file: container/Containerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ github.event_name != 'pull_request' }}
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: container/Containerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
