name: Release
permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create release
        run: |
          gh release create --notes-from-tag --draft ${{ github.ref_name }}
  build:
    name: Build artifacts
    needs: release
    runs-on: ${{ matrix.config.runner }}
    strategy:
      matrix:
        config:
          - { arch: x86_64,  platform: linux/amd64, runner: ubuntu-latest    }
          - { arch: aarch64, platform: linux/arm64, runner: ubuntu-24.04-arm }
    container:
      image: ghcr.io/void-linux/void-musl-full:latest
      options: --platform ${{ matrix.config.platform }}
      env:
        PATH: '/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/tmp/bin'
    steps:
      - name: Install Dependencies
        run: |
          xbps-install -Suy xbps && \
            xbps-install -uy git bash base-devel rustup cargo-auditable github-cli && \
            rustup-init -y
      - name: Checkout
        uses: classabbyamp/treeless-checkout-action@v1
      - name: Build
        run: cargo auditable build --profile release-bin
      - name: Upload to release
        run: |
          cp ./target/release-bin/convoyeur convoyeur.${{ matrix.config.arch }}
          gh release upload ${{ github.ref_name }} ./convoyeur.${{ matrix.config.arch }}#convoyeur.${{ matrix.config.arch }}
